---
 apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: httpd-namespace
spec:
  type: NodePort
  selector:
    app: httpd_app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: httpd-namespace
  labels:
    app: httpd_app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd_app
  template:
    metadata:
      labels:
        app: httpd_app
    spec:
      containers:
        - name: httpd-container
          image: httpd:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: website-namespace
spec:
  type: NodePort
  selector:
    app: website_app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  namespace: website-namespace
  labels:
    app: website_app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website_app
  template:
    metadata:
      labels:
        app: website_app
    spec:
      containers:
        - name: website-container
          image: megmahajan/test
          ports:
            - containerPort: 80
